language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name: linux stable rust
      os  : linux
      dist: bionic # required for tarpaulin binary distribution to work.
      rust: stable

      install:
          # wasm-pack doesn't support passing features to cargo test, so we can't use that.
          #
        - cargo install --force wasm-bindgen-cli
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - rustup target add wasm32-unknown-unknown

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev
            - nodejs

      script:
        - bash ci.bash
        - bash ci_wasm.bash
        - bash coverage.bash


    - name: linux nightly rust
      os  : linux
      rust: nightly

      install:
        - cargo install --force wasm-bindgen-cli
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - rustup target add wasm32-unknown-unknown

      addons:
        firefox: latest
        apt:
          packages:
            - nodejs

      script:
        - bash ci.bash
        - bash ci_wasm.bash


    - name: osx stable rust
      os  : osx
      rust: stable

      install:
        - cargo install --force wasm-bindgen-cli
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        - rustup target add wasm32-unknown-unknown

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash
        - bash ci_wasm.bash


    # currently wasm-bindgen-cli does not compile on windows, so we skip wasm on windows for now.
    #
    - name: windows stable rust
      os  : windows
      rust: stable

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash





