language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin

  # - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
  #     cargo install cargo-tarpaulin
  #   fi


branches:
  only:
    - master
    - dev

install:
  - cargo install --force wasm-bindgen-cli
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - rustup target add wasm32-unknown-unknown
  # - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)

jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev
            - pkg-config
            - cmake
            - zlib1g-dev

      script:
        - bash ci.bash

      after_success: |
        cargo install --force cargo-tarpaulin
        cargo tarpaulin --all-features --exclude-files src/bindgen.rs --out Xml
        bash <(curl -s https://codecov.io/bash)


    - name: linux nightly rust
      os  : linux
      rust: nightly

      addons:
        firefox: latest

      script:
        - bash ci.bash
        - cargo doc  --no-deps --all-features

          # for doc tests
          #
        - cargo test --all-features


    - name: osx stable rust
      os  : osx
      rust: stable

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash


    - name: osx nightly rust
      os  : osx
      rust: nightly

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash


    # - name: windows stable rust
    #   os  : windows
    #   rust: stable

    #   # for wasm tests
    #   #
    #   addons:
    #     firefox: latest

    #   script:
    #     - bash ci.bash


    # - name: windows nightly rust
    #   os  : windows
    #   rust: nightly

    #   # for wasm tests
    #   #
    #   addons:
    #     firefox: latest

    #   script:
    #     - bash ci.bash





