language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


branches:
  only:
    - master
    - dev

install:
  - cargo install --force wasm-bindgen-cli
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - rustup target add wasm32-unknown-unknown


jobs:

  include:

    - name: linux stable rust
      os  : linux
      rust: stable

      addons:
        firefox: latest

      script:
        - bash ci.bash



    - name: linux nightly rust
      os  : linux
      rust: nightly

      addons:
        firefox: latest

      script:
        - bash ci.bash
        - cargo doc  --no-deps --all-features

          # for doc tests
          #
        - cargo test --all-features


    - name: osx stable rust
      os  : osx
      rust: stable

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash


    - name: osx nightly rust
      os  : osx
      rust: nightly

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash


    - name: windows stable rust
      os  : windows
      rust: stable

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash


    - name: windows nightly rust
      os  : windows
      rust: nightly

      # for wasm tests
      #
      addons:
        firefox: latest

      script:
        - bash ci.bash





